#ifndef __DEFINES_MODELINFO_H__
#define __DEFINES_MODELINFO_H__

#define LINK_MODELINFO_FLAG_MM_ADULT_FIX 0x1
#define IS_HUMAN_ADULT_LINK_MODEL (gLinkFormProxies[PLAYER_FORM_HUMAN].current.flags & LINK_MODELINFO_FLAG_MM_ADULT_FIX)

#endif
