#ifndef __EXTERNAL_DISPLAY_LISTS_H__
#define __EXTERNAL_DISPLAY_LISTS_H__

#include "modelreplacer_api.h"

extern ZModelReplacerHandle gProxyBottleGlass;
extern ZModelReplacerHandle gProxyBottleContents;
extern ZModelReplacerHandle gProxyDekuStick;
extern ZModelReplacerHandle gProxyBowString;
extern ZModelReplacerHandle gProxyBowArrow;
extern ZModelReplacerHandle gProxyBowArrowLowPoly;
extern ZModelReplacerHandle gProxyHookshotChain;
extern ZModelReplacerHandle gProxyHookshotHook;
extern ZModelReplacerHandle gProxyHookshotReticle;

#endif
