#ifndef __EXTERNAL_DISPLAY_LISTS_H__
#define __EXTERNAL_DISPLAY_LISTS_H__

#include "modelreplacer_api.h"

extern ModelReplacerHandle gProxyBottleGlass;
extern ModelReplacerHandle gProxyBottleContents;
extern ModelReplacerHandle gProxyDekuStick;
extern ModelReplacerHandle gProxyBowString;
extern ModelReplacerHandle gProxyBowArrow;
extern ModelReplacerHandle gProxyBowArrowLowPoly;
extern ModelReplacerHandle gProxyHookshotChain;
extern ModelReplacerHandle gProxyHookshotHook;
extern ModelReplacerHandle gProxyHookshotReticle;
extern ModelReplacerHandle gProxyMirrorShieldRay;

#endif
