#ifndef __EXTERNAL_DISPLAY_LISTS_H__
#define __EXTERNAL_DISPLAY_LISTS_H__

#include "modelreplacer_api.h"
#include "playermodelmanager.h"

typedef enum {
    PLAYERLIB_DL_LFIST_SWORD_KOKIRI,
    PLAYERLIB_DL_LFIST_SWORD_RAZOR,
    PLAYERLIB_DL_LFIST_SWORD_GILDED,
    PLAYERLIB_DL_SHIELD_HERO_BACK,
    PLAYERLIB_DL_SHIELD_MIRROR_BACK,
    PLAYERLIB_DL_RFIST_SHIELD_HERO,
    PLAYERLIB_DL_RFIST_SHIELD_MIRROR,
    PLAYERLIB_DL_SWORD_KOKIRI_SHEATHED,
    PLAYERLIB_DL_SWORD_RAZOR_SHEATHED,
    PLAYERLIB_DL_SWORD_GILDED_SHEATHED,
    PLAYERLIB_DL_SWORD_KOKIRI_SHEATH,
    PLAYERLIB_DL_SWORD_RAZOR_SHEATH,
    PLAYERLIB_DL_SWORD_GILDED_SHEATH,
    PLAYERLIB_DL_LFIN,
    PLAYERLIB_DL_LFIN_SWIM,
    PLAYERLIB_DL_RFIN,
    PLAYERLIB_DL_RFIN_SWIM,
    PLAYERLIB_DL_PAD_WOOD,
    PLAYERLIB_DL_PAD_GRASS,
    PLAYERLIB_DL_PAD_OPENING,
    PLAYERLIB_DL_MAX
} PlayerLibDisplayList;

extern Gfx gPlayerLibDLs[];

void refreshExternalDLs(Link_FormProxy *proxy, bool useOriginalForms);

#endif
